[package]
name = "transient"
version = "0.0.1"
authors = ["Joshua Rudolph <jrudolph093@gmail.com>"]
license = "MIT"
readme = "README.md"
edition = "2021"

# repository = "https://github.com/rust-lang/..."
# documentation = "https://docs.rs/..."
# homepage = "https://github.com/rust-lang/..."
# description = """..."""

[lib]
doctest = true

[workspace]
members = ["derive"]

[dependencies]
transient_derive = { path = "derive", optional = true }
ndarray = { version = "*", optional = true }
numpy = { version = "*", optional = true }
pyo3 = { version = ">0.21.0", optional = true }

[dev-dependencies]
trybuild = { version = "1.0.49", features = ["diff"] }

[features]
default = ["derive"]
derive = ["transient_derive"]
ndarray = ["dep:ndarray"]
pyo3 = ["dep:pyo3"]
numpy = ["dep:numpy", "ndarray", "pyo3"]
