[package]
name = "transient_any_derive"
version = "0.0.1"
edition = "2021"
autotests = false

[lib]
proc-macro = true
doctest = false

[[test]]
name = "tests"
path = "tests/progress.rs"

[dev-dependencies]
trybuild = { version = "1.0.49", features = ["diff"] }
transient_any = { path = ".." }

[dependencies]
proc-macro2 = "1.*"
quote = "1.*"
syn = { version = "2.*", features = ["full"] }
